version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroes_challenge
      MYSQL_USER: heroes
      MYSQL_PASSWORD: challenge
  node:
    build: .
    container_name: heroes_challenge_api
    image: node:10-jessie
    ports:
      - '3333:3333'
    command: sh -c "sleep 15; node ace migration:run --force && npm run start"
    volumes:
      - .:/app
    links:
      - mysql
    depends_on:
      - mysql
